### ISSUE TITLE
Wonder if you could... split the text being passed

### ISSUE THREAD

**Issue by xransum** [sean-frank/python-learning#1]
https://github.com/sean-frank/python-learning/blob/3e9780e994092e76861b534161e6dc13c9179d3b/12_get_extension_from_filename.py#L33

**Comment by xransum** [comment]
Hint: https://docs.python.org/2/library/string.html#string.split

**Comment by sean-frank** [comment]
Hey Kevin I just pushed a new version of the practice using the split method. Thanks for the hint!

**Comment by xransum** [comment]
![Lets Goooo](https://media.tenor.com/Ele9C8aLE_YAAAAM/letgo-lets-goooo.gif)
